import { z } from "zod";

// Address Schema
export const addressFormSchema = z.object({
  id: z.bigint().optional(), // Optional, as it might be generated by the database
  created_at: z.string().optional(), // Usually handled by the database
  street: z.string().min(1, "Street is required"), // Validate that street is not empty
  city: z.string().min(1, "City is required"), // Validate that city is not empty
  postcode: z.string().min(1, "Postcode is required"), // Validate that postcode is not empty
  country: z.string().min(1, "Country is required"), // Validate that country is not empty
  user_id: z.bigint() // Foreign key referencing the user
});