// Purchases Schema
export const purchaseFormSchema = z.object({
    id: z.bigint().optional(), // Optional, as it might be generated by the database
    created_at: z.string().optional(), // Usually handled by the DB, so optional
    user_id: z.bigint(), // Foreign key referencing the user
    delivery_address: z.bigint(), // Foreign key referencing the delivery address
    total: z.bigint(), // Total cost of the purchase
    products: z.array(
      z.object({
        product_id: z.bigint(), // Foreign key referencing the product
        quantity: z.number().min(1, "Quantity must be at least 1"), // Validate quantity
        price: z.bigint() // Price of the product
      })
    ) // JSONB array to store product details
  });

  